server:
  port: 8888

spring:
  application:
    name: configserver

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        #fetch config from remote git repository
#        git:
#          uri: https://github.com/alirezaazizollahi/app-configuration.git
#          default-label: master
#          username: alirezaazizollahi
#          password: ${APP_CONFIGURATION_TOKEN}

# encrypt property using AES algorithm
#encrypt:
#  key: 0123456789abcdef

# encrypt property using RSA algorithm and key store
encrypt:
  key-store:
    location: config-server.jks
    password: changeit
    alias: config-server-key
