server:
  port: 8888

spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/alirezaazizollahi/app-configuration.git
          default-label: master
          username: alirezaazizollahi
          password: ${APP_CONFIGUATION_TOKEN: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}
